DT-2770: remove junit-jupiter-params dependency
This was causing java.lang.NoClassDefFoundError: org/junit/jupiter/api/Named errors when running tests with the ParameterizedTest annotation. I checked the parent Gradle junit-jupiter version and it was also 5.8.1 - https://github.com/ministryofjustice/dps-gradle-spring-boot/blob/b1e945a9f28a0971971d91cb9cd00a8bb66ef854/build.gradle.kts#L66 - so there must have been some Gradle dependency resolution issue. Other folks in the MoJ organisation use ParameterizedTest but haven't included the params dependency so seems it's redundant